spring:
  application:
    name: library
  datasource:
    url: jdbc:h2:file:/data/library;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
   # show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/liquibase/changelog.xml
logging:
  level:
    org:
      springframework:
        security: INFO
    root: INFO
    com:
      musiienko:
        library: INFO

