-- liquibase formatted sql

-- changeset white-rabbit:1721853363147-1
CREATE TABLE books
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn     VARCHAR(255)                            NOT NULL,
    title    VARCHAR(255)                            NOT NULL,
    author   VARCHAR(255)                            NOT NULL,
    category VARCHAR(255)                            NOT NULL,
    user_id  BIGINT,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

-- changeset white-rabbit:1721853363147-2
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset white-rabbit:1721853363147-3
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset white-rabbit:1721853363147-4
ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

